# Generated by Django 4.0.4 on 2022-06-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('birthdate', models.DateField()),
                ('contact', models.CharField(max_length=11)),
                ('gender', models.TextField(max_length=10)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('illness', models.CharField(max_length=100)),
                ('dateAdmitted', models.DateField()),
                ('dateDischarged', models.DateField(null=True)),
            ],
        ),
    ]
