# Generated by Django 4.0.4 on 2022-05-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
